"""SQLAlchemy 2.0 ORM models for the curated SEC XBRL data (PostgreSQL target).

Source of the data
------------------
One row per fact in ``data/xbrl/<TICKER>.json`` (written by
``app/ingest/xbrl_store.py``). Each of those files is a scope-filtered copy of
the SEC ``xbrl/companyfacts`` endpoint payload -- restricted to 10-K/10-Q
filings and the five most recent fiscal years -- with this shape::

    {cik, ticker, entity_name, source_url, retrieved,
     scope:  {forms: [...], fiscal_years: [...]},
     counts: {taxonomies, concepts, facts},
     facts:  {<taxonomy>: {<ConceptName>: {label, description,
                            units: {<unit>: [ {end, val, accn, fy, fp, form,
                                               filed, start?, frame?}, ... ]}}}}}

Namespace
---------
All tables and the three enum types live in a dedicated PostgreSQL schema
called ``xbrl`` (see ``Base.metadata`` below), not ``public``. The schema is
created automatically on ``metadata.create_all`` via a ``before_create`` DDL
hook, guarded to PostgreSQL. ``DROP SCHEMA xbrl CASCADE`` wipes everything for
a clean re-ingest.

Ingest-time unit filter -- IMPORTANT
------------------------------------
``Fact`` rows are only created when the XBRL unit is in ``ALLOWED_UNITS``.
Every other unit seen in the source (custom units such as ``warehouse``,
``Plaintiff``, ``judicialCase``, ``MWh``, segment counts, ...) tags a
disclosure count, not financial-statement data, and is deliberately dropped.
Each load records the allow-list it applied and how many facts it skipped in
``IngestRun`` (``units_allowlist`` / ``facts_dropped_unit``), so a later
"why is this value missing" question is answerable. Widen ``ALLOWED_UNITS``
to bring more in. This is a load-time policy, not a schema constraint: the
column itself is a plain string.

Key choices (see the module conversation for the full rationale)
---------------------------------------------------------------
* ``Company`` PK is the SEC ``cik`` -- a stable, globally unique, never-reused
  integer. ``Company.id`` is an auto-populated IDENTITY column kept UNIQUE but
  referenced by nothing; it exists so a synthetic surrogate can be promoted to
  the FK target later without a dedupe step.
* ``Filing`` PK is the accession number (globally unique).
* ``Concept`` is global -- one row per ``(taxonomy, name)`` pair. Labels and
  descriptions are byte-identical across all 20 companies, so they are stored
  once here, not per company.
* ``Fact.value`` is ``Numeric(30, 6)``: values run from 1e-5 (par value) and
  sub-1 ratios (tax rates, yields) up to ~6.3e13, some with 4 decimal places.
  A ``BigInteger`` would zero out every EPS / rate / per-share fact.
* ``Fact.is_latest`` marks the most-recently-filed value for a period; older
  restated rows are kept but flagged ``False``.
* Every surrogate PK / auto key uses ``Identity()`` -> ``GENERATED BY DEFAULT
  AS IDENTITY`` (SQL-standard, PG 10+). No ``SERIAL``/``BIGSERIAL`` anywhere.
* Nullability is declared twice on purpose: the ``Mapped[...]`` annotation and
  an explicit ``nullable=`` on every non-PK column. PK columns state it once
  via ``primary_key=True``. Column string lengths are bounded from observed
  data (see per-column comments); genuinely long prose is ``Text``.

Future work (not in this folder yet)
------------------------------------
* Alembic lives at the *project root*: ``alembic.ini`` + ``migrations/``
  (``env.py`` imports ``app.db.Base`` for ``target_metadata``). Not under
  ``app/``.
* Pydantic schemas go in ``app/db/schemas.py`` -- a single module until it
  outgrows a file -- for validating the source ``data/xbrl/*.json`` on ingest
  and shaping model data. Only introduce ``app/api/`` if a real HTTP API is
  added, and keep those request/response DTOs there, out of ``db/``.
* Engine + ``sessionmaker`` wiring goes in ``app/db/session.py`` alongside the
  Alembic work.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    DDL,
    BigInteger,
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Identity,
    Index,
    Integer,
    MetaData,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    event,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# --------------------------------------------------------------------------- #
# Ingest-time policy constant (kept beside the schema it filters into)
# --------------------------------------------------------------------------- #
#: XBRL units a ``Fact`` row is allowed to have. Everything else is a
#: non-financial disclosure count and is dropped at ingest -- the drop is
#: recorded per run in ``IngestRun``. Widen this set to capture more.
ALLOWED_UNITS: frozenset[str] = frozenset(
    {"USD", "shares", "pure", "USD/shares", "Rate", "EUR"}
)

#: PostgreSQL schema (namespace) that owns every table and enum type here.
SCHEMA = "xbrl"

# Deterministic names for indexes/constraints SQLAlchemy would otherwise
# auto-name (chiefly foreign keys). Makes future Alembic autogenerate diffs
# stable. Explicitly-named constraints below keep the name they are given.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base. All subclasses land in the ``xbrl`` schema."""

    metadata = MetaData(schema=SCHEMA, naming_convention=NAMING_CONVENTION)


# Create the schema before any CREATE TABLE. No-op on non-PostgreSQL backends
# (e.g. a SQLite test DB), where "schema" means something incompatible.
event.listen(
    Base.metadata,
    "before_create",
    DDL(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}").execute_if(dialect="postgresql"),
)
event.listen(
    Base.metadata,
    "after_drop",
    DDL(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE").execute_if(dialect="postgresql"),
)


# --------------------------------------------------------------------------- #
# Shared PostgreSQL enum types
# --------------------------------------------------------------------------- #
# Native PG enums. Adding a value later (e.g. "10-K/A") needs
# ``ALTER TYPE ... ADD VALUE`` -- if that churn is expected, swap these for
# String + CheckConstraint.
taxonomy_enum = SAEnum("dei", "us-gaap", "srt", name="taxonomy", schema=SCHEMA)
filing_form_enum = SAEnum("10-K", "10-Q", name="filing_form", schema=SCHEMA)
fiscal_period_enum = SAEnum("FY", "Q1", "Q2", "Q3", name="fiscal_period", schema=SCHEMA)


# --------------------------------------------------------------------------- #
# Company
# --------------------------------------------------------------------------- #
class Company(Base):
    __tablename__ = "company"

    #: SEC Central Index Key. The PK and the FK target used throughout.
    cik: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)

    #: Auto-populated surrogate (PostgreSQL IDENTITY). Gets a value on every
    #: insert and is kept UNIQUE, so it can be promoted to the FK target later
    #: with no dedupe step -- but nothing references it today and the
    #: application never keys on it.
    id: Mapped[int] = mapped_column(Integer, Identity(), unique=True, nullable=False)

    # source_url is always the companyfacts URL (observed max 61 chars);
    # entity_name is the SEC conformed name (max 150 by EDGAR rule).
    ticker: Mapped[str | None] = mapped_column(String(10), nullable=True, index=True)
    entity_name: Mapped[str | None] = mapped_column(String(150), nullable=True)
    source_url: Mapped[str | None] = mapped_column(String(255), nullable=True)

    filings: Mapped[list[Filing]] = relationship(
        back_populates="company",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    facts: Mapped[list[Fact]] = relationship(
        back_populates="company",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    ingest_runs: Mapped[list[IngestRun]] = relationship(
        back_populates="company",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    def __repr__(self) -> str:  # pragma: no cover - convenience only
        return f"Company(cik={self.cik}, ticker={self.ticker!r})"


# --------------------------------------------------------------------------- #
# Filing  (one XBRL accession)
# --------------------------------------------------------------------------- #
class Filing(Base):
    __tablename__ = "filing"

    #: SEC accession number, e.g. "0000320193-23-000106". Globally unique.
    accession_number: Mapped[str] = mapped_column(String(20), primary_key=True)

    company_cik: Mapped[int] = mapped_column(
        ForeignKey("company.cik", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    form: Mapped[str] = mapped_column(filing_form_enum, nullable=False)
    fiscal_year: Mapped[int] = mapped_column(Integer, nullable=False)
    fiscal_period: Mapped[str] = mapped_column(fiscal_period_enum, nullable=False)
    filed_date: Mapped[date] = mapped_column(Date, nullable=False)

    company: Mapped[Company] = relationship(back_populates="filings")
    facts: Mapped[list[Fact]] = relationship(
        back_populates="filing",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    __table_args__ = (
        Index("ix_filing_company_period", "company_cik", "fiscal_year", "fiscal_period"),
        Index("ix_filing_filed_date", "filed_date"),
    )

    def __repr__(self) -> str:  # pragma: no cover - convenience only
        return (
            f"Filing(accession_number={self.accession_number!r}, "
            f"form={self.form!r}, fy={self.fiscal_year}, fp={self.fiscal_period!r})"
        )


# --------------------------------------------------------------------------- #
# Concept  (one taxonomy element, shared across every company)
# --------------------------------------------------------------------------- #
class Concept(Base):
    __tablename__ = "concept"

    #: Surrogate PK. The natural key is ``(taxonomy, name)``; a single int is
    #: cheaper for ``Fact`` to carry and index than the composite.
    id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)

    taxonomy: Mapped[str] = mapped_column(taxonomy_enum, nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)

    #: Verified byte-identical across all 20 companies for every shared
    #: concept, so stored once here. Null for ~200 (mostly dei / srt) concepts.
    #: label observed max 180 chars (p99 131); description runs to ~1.7k -> Text.
    label: Mapped[str | None] = mapped_column(String(512), nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    # passive_deletes="all": never null out fact.concept_id from the ORM side.
    # Concepts are shared reference data and should not be deleted while facts
    # point at them; the DB's ON DELETE RESTRICT is what enforces that.
    facts: Mapped[list[Fact]] = relationship(
        back_populates="concept", passive_deletes="all"
    )

    __table_args__ = (
        UniqueConstraint("taxonomy", "name", name="uq_concept_taxonomy_name"),
    )

    def __repr__(self) -> str:  # pragma: no cover - convenience only
        return f"Concept(id={self.id}, taxonomy={self.taxonomy!r}, name={self.name!r})"


# --------------------------------------------------------------------------- #
# Fact  (one observed value)
# --------------------------------------------------------------------------- #
class Fact(Base):
    __tablename__ = "fact"

    id: Mapped[int] = mapped_column(BigInteger, Identity(), primary_key=True)

    filing_accession: Mapped[str] = mapped_column(
        ForeignKey("filing.accession_number", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    company_cik: Mapped[int] = mapped_column(
        ForeignKey("company.cik", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # No standalone index: ix_fact_concept_frame (concept_id, frame) covers
    # concept_id-prefix lookups and the FK check.
    concept_id: Mapped[int] = mapped_column(
        ForeignKey("concept.id", ondelete="RESTRICT"),
        nullable=False,
    )

    #: Plain string (no lookup table). Constrained to ``ALLOWED_UNITS`` at
    #: ingest, not in the schema.
    unit: Mapped[str] = mapped_column(String(32), nullable=False)

    #: ``period_start`` NULL  -> instant (balance-sheet) fact
    #: ``period_start`` set   -> duration (flow) fact
    period_start: Mapped[date | None] = mapped_column(Date, nullable=True)
    period_end: Mapped[date] = mapped_column(Date, nullable=False)
    is_instant: Mapped[bool] = mapped_column(Boolean, nullable=False)

    #: See module docstring: Numeric, never BigInteger.
    value: Mapped[Decimal] = mapped_column(Numeric(30, 6), nullable=False)

    #: SEC "frame" tag for cross-company comparison, e.g. "CY2021Q2I". Often null.
    frame: Mapped[str | None] = mapped_column(String(16), nullable=True)

    #: True iff this is the most-recently-filed value for its
    #: ``(company_cik, concept_id, unit, period_start, period_end)`` group.
    #: Maintained at ingest -- loading a newer filing flips older rows False.
    #: Restated periods keep every row; analytics filter on ``is_latest``.
    is_latest: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )

    company: Mapped[Company] = relationship(back_populates="facts")
    filing: Mapped[Filing] = relationship(back_populates="facts")
    concept: Mapped[Concept] = relationship(back_populates="facts")

    __table_args__ = (
        # Dedupe / natural key. COALESCE because a plain UNIQUE would treat NULL
        # period_start values as distinct; instants collapse onto period_end.
        Index(
            "uq_fact_natural",
            "filing_accession",
            "concept_id",
            "unit",
            text("coalesce(period_start, period_end)"),
            "period_end",
            unique=True,
        ),
        # Primary analytical access path: one concept's history for one company.
        Index(
            "ix_fact_latest_lookup",
            "company_cik",
            "concept_id",
            "period_end",
            postgresql_where=text("is_latest"),
        ),
        # Cross-company comparison via SEC frames.
        Index("ix_fact_concept_frame", "concept_id", "frame"),
        # Names run through NAMING_CONVENTION's "ck_%(table_name)s_%(constraint_name)s"
        # -> ck_fact_instant_flag / ck_fact_period_order.
        CheckConstraint(
            "(period_start IS NULL) = is_instant",
            name="instant_flag",
        ),
        CheckConstraint(
            "period_start IS NULL OR period_start <= period_end",
            name="period_order",
        ),
    )

    def __repr__(self) -> str:  # pragma: no cover - convenience only
        return (
            f"Fact(id={self.id}, concept_id={self.concept_id}, unit={self.unit!r}, "
            f"period_end={self.period_end!r}, value={self.value}, "
            f"is_latest={self.is_latest})"
        )


# --------------------------------------------------------------------------- #
# IngestRun  (provenance, idempotency, audit of what was dropped)
# --------------------------------------------------------------------------- #
class IngestRun(Base):
    __tablename__ = "ingest_run"

    id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)

    company_cik: Mapped[int] = mapped_column(
        ForeignKey("company.cik", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    #: From the top of the source file (always the companyfacts URL).
    source_url: Mapped[str] = mapped_column(String(255), nullable=False)
    retrieved_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    #: From the file's ``scope`` block.
    scope_forms: Mapped[list[str]] = mapped_column(JSONB, nullable=False)
    scope_fiscal_years: Mapped[list[int]] = mapped_column(JSONB, nullable=False)

    #: From the file's ``counts`` block -- checksum the load against these.
    taxonomy_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    concept_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    fact_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    #: Audit of the unit filter for THIS run.
    units_allowlist: Mapped[list[str]] = mapped_column(JSONB, nullable=False)
    facts_dropped_unit: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )

    company: Mapped[Company] = relationship(back_populates="ingest_runs")

    def __repr__(self) -> str:  # pragma: no cover - convenience only
        return (
            f"IngestRun(id={self.id}, company_cik={self.company_cik}, "
            f"ingested_at={self.ingested_at!r})"
        )
