/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Auth:Cookie.Login */
        readonly post: operations["auth_cookie_login_api_auth_login_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Auth:Cookie.Logout */
        readonly post: operations["auth_cookie_logout_api_auth_logout_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/register": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Register:Register */
        readonly post: operations["register_register_api_auth_register_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/github/authorize": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Oauth:Github.Cookie.Authorize */
        readonly get: operations["oauth_github_cookie_authorize_api_auth_github_authorize_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/github/callback": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Oauth:Github.Cookie.Callback
         * @description The response varies based on the authentication backend used.
         */
        readonly get: operations["oauth_github_cookie_callback_api_auth_github_callback_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/conversations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * History
         * @description The reader's past questions, newest first.
         */
        readonly get: operations["history_api_conversations_get"];
        readonly put?: never;
        /**
         * Ask
         * @description A new question: its conversation and first round, queued.
         */
        readonly post: operations["ask_api_conversations_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/conversations/{conversation_id}/answers": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Answer
         * @description Answers to the last round's questions: the next round, queued.
         */
        readonly post: operations["answer_api_conversations__conversation_id__answers_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/conversations/{conversation_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Conversation
         * @description A past conversation reopened: every round, in order, as the thread shows it.
         */
        readonly get: operations["conversation_api_conversations__conversation_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/jobs/{job_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Job
         * @description One round as it stands -- for a reload or a dropped stream.
         */
        readonly get: operations["job_api_jobs__job_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/jobs/{job_id}/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Events
         * @description Server-sent events: each stage, then ``done`` (with the reply) or ``failed``.
         */
        readonly get: operations["events_api_jobs__job_id__events_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/jobs/{job_id}/feedback": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Feedback
         * @description Report a problem: the job becomes a ``--flagged`` one in the owner's trace CLI.
         */
        readonly post: operations["feedback_api_jobs__job_id__feedback_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Health
         * @description Up, and able to reach the database as vf_web_role. No sign-in: it says
         *     nothing a reader could use, and Docker's health check calls it.
         */
        readonly get: operations["health_api_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Me */
        readonly get: operations["me_api_me_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerRow
         * @description One figure: a row of the table, and a point or bar in any view.
         */
        readonly AnswerRow: {
            /** Element Id */
            readonly element_id: string;
            /** Metric */
            readonly metric: string;
            /** Company Cik */
            readonly company_cik: number | null;
            /** Company */
            readonly company: string;
            /** Companies */
            readonly companies: readonly string[];
            /** Fiscal Year */
            readonly fiscal_year: number;
            /**
             * Fiscal Period
             * @enum {string}
             */
            readonly fiscal_period: "FY" | "Q1" | "Q2" | "Q3" | "Q4";
            /** Period Label */
            readonly period_label: string;
            /**
             * Granularity
             * @enum {string}
             */
            readonly granularity: "annual" | "quarterly";
            /** Period Start */
            readonly period_start: string | null;
            /**
             * Period End
             * Format: date
             */
            readonly period_end: string;
            /** Is Instant */
            readonly is_instant: boolean;
            /** Value */
            readonly value: string | null;
            /** Display */
            readonly display: string;
            /** Unit */
            readonly unit: string;
            /**
             * Unit Kind
             * @enum {string}
             */
            readonly unit_kind: "money" | "ratio" | "multiple" | "per_share" | "count";
            /** Derivation */
            readonly derivation: string | null;
            /** Compared With */
            readonly compared_with: string | null;
            /** Citations */
            readonly citations: readonly string[];
        };
        /**
         * AnswerView
         * @description Everything the Web Client draws for the answered parts of a reply.
         */
        readonly AnswerView: {
            /**
             * Shape
             * @enum {string}
             */
            readonly shape: "scalar" | "series" | "table" | "ranking";
            /** Rows */
            readonly rows: readonly components["schemas"]["AnswerRow"][];
            /** Views */
            readonly views: readonly (components["schemas"]["StatView"] | components["schemas"]["LineView"] | components["schemas"]["BarView"])[];
            /** Citations */
            readonly citations: {
                readonly [key: string]: components["schemas"]["CitationView"];
            };
            /** Notes */
            readonly notes: readonly components["schemas"]["Note"][];
            /** Conditions */
            readonly conditions: readonly string[];
        };
        /** AnswersIn */
        readonly AnswersIn: {
            /** Answers */
            readonly answers: readonly components["schemas"]["OptionAnswerIn"][];
        };
        /**
         * Ask
         * @description A question back to the asker (§3).
         */
        readonly Ask: {
            /** Ask Id */
            readonly ask_id: string;
            /**
             * Kind
             * @enum {string}
             */
            readonly kind: "clarification" | "ambiguity";
            /** Question */
            readonly question: string;
            /** Options */
            readonly options: readonly components["schemas"]["Option"][];
        };
        /** BarView */
        readonly BarView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly kind: "bar";
            /** Title */
            readonly title: string;
            /**
             * Unit Kind
             * @enum {string}
             */
            readonly unit_kind: "money" | "ratio" | "multiple" | "per_share" | "count";
            /**
             * Order
             * @enum {string}
             */
            readonly order: "descending" | "ascending";
            /** Rows */
            readonly rows: readonly number[];
        };
        /** Body_auth_cookie_login_api_auth_login_post */
        readonly Body_auth_cookie_login_api_auth_login_post: {
            /** Grant Type */
            readonly grant_type?: string | null;
            /** Username */
            readonly username: string;
            /**
             * Password
             * Format: password
             */
            readonly password: string;
            /**
             * Scope
             * @default
             */
            readonly scope?: string;
            /** Client Id */
            readonly client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            readonly client_secret?: string | null;
        };
        /**
         * CitationView
         * @description What one binding contributed, for the "answered as" panel (§6).
         */
        readonly CitationView: {
            /** Key */
            readonly key: string;
            /** Concepts */
            readonly concepts: readonly components["schemas"]["ConceptRef"][];
            /** Expression */
            readonly expression: string;
            /** Unit */
            readonly unit: string;
            /**
             * Resolved By
             * @enum {string}
             */
            readonly resolved_by: "alias" | "embedding" | "pinned";
            /** Notes */
            readonly notes: readonly components["schemas"]["Note"][];
        };
        /**
         * ConceptRef
         * @description One resolved ``Concept``, denormalized enough that the SQL step never
         *     has to look it up to know what it is.
         */
        readonly ConceptRef: {
            /** Concept Id */
            readonly concept_id: number;
            /**
             * Taxonomy
             * @enum {string}
             */
            readonly taxonomy: "dei" | "us-gaap" | "srt";
            /** Name */
            readonly name: string;
            /** Label */
            readonly label: string | null;
        };
        /**
         * ConversationSummary
         * @description One line of "my past questions".
         */
        readonly ConversationSummary: {
            /**
             * Conversation Id
             * Format: uuid
             */
            readonly conversation_id: string;
            /** Question */
            readonly question: string;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Rounds */
            readonly rounds: number;
            /**
             * Status
             * @enum {string}
             */
            readonly status: "queued" | "parsing" | "mapping" | "fetching" | "presenting" | "done" | "failed";
            /** Reply Status */
            readonly reply_status: ("answered" | "partial" | "asked" | "refused") | null;
        };
        /**
         * ConversationView
         * @description ``GET /api/conversations/{id}`` -- a past conversation, reopened as its thread.
         */
        readonly ConversationView: {
            /**
             * Conversation Id
             * Format: uuid
             */
            readonly conversation_id: string;
            /** Question */
            readonly question: string;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Rounds */
            readonly rounds: readonly components["schemas"]["RoundView"][];
        };
        /** ErrorModel */
        readonly ErrorModel: {
            /** Detail */
            readonly detail: string | {
                readonly [key: string]: string;
            };
        };
        /**
         * FeedbackIn
         * @description Report a problem on one job (§8).
         */
        readonly FeedbackIn: {
            /** Note */
            readonly note?: string | null;
        };
        /**
         * GivenAnswer
         * @description One answer a round was started with -- as ``Job.answers`` stores it, and as
         *     the thread shows it. Its text is always kept, so free text needs no change (§3).
         */
        readonly GivenAnswer: {
            /** Ask Id */
            readonly ask_id: string;
            /**
             * Kind
             * @default option
             * @constant
             */
            readonly kind: "option";
            /** Option Id */
            readonly option_id: string | null;
            /** Text */
            readonly text: string;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /** JobCreated */
        readonly JobCreated: {
            /**
             * Conversation Id
             * Format: uuid
             */
            readonly conversation_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            readonly job_id: string;
        };
        /**
         * JobView
         * @description ``GET /api/jobs/{id}`` -- for a reload or a dropped stream.
         */
        readonly JobView: {
            /**
             * Job Id
             * Format: uuid
             */
            readonly job_id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            readonly conversation_id: string;
            /**
             * Status
             * @enum {string}
             */
            readonly status: "queued" | "parsing" | "mapping" | "fetching" | "presenting" | "done" | "failed";
            readonly reply: components["schemas"]["Reply"] | null;
        };
        /** LineView */
        readonly LineView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly kind: "line";
            /** Title */
            readonly title: string;
            /**
             * Unit Kind
             * @enum {string}
             */
            readonly unit_kind: "money" | "ratio" | "multiple" | "per_share" | "count";
            /**
             * Granularity
             * @enum {string}
             */
            readonly granularity: "annual" | "quarterly";
            /** Series */
            readonly series: readonly components["schemas"]["Series"][];
        };
        /** NewConversationIn */
        readonly NewConversationIn: {
            /** Question */
            readonly question: string;
        };
        /**
         * Note
         * @description A caveat that must survive all the way to the reader.
         *
         *     Distinct from ``Unresolved``: the binding *works*, but presenting its
         *     numbers without this sentence would mislead. The user-facing model is
         *     expected to pass these on rather than summarize them away.
         */
        readonly Note: {
            /**
             * Kind
             * @enum {string}
             */
            readonly kind: "concept_switch" | "unverified_switch" | "partial_coverage" | "period_misalignment" | "mixed_granularity" | "narrower_than_asked" | "incomplete_result";
            /** Message */
            readonly message: string;
        };
        /** OAuth2AuthorizeResponse */
        readonly OAuth2AuthorizeResponse: {
            /** Authorization Url */
            readonly authorization_url: string;
        };
        /** Option */
        readonly Option: {
            /** Option Id */
            readonly option_id: string;
            /** Label */
            readonly label: string;
            /** Description */
            readonly description: string;
        };
        /** OptionAnswerIn */
        readonly OptionAnswerIn: {
            /**
             * Kind
             * @default option
             * @constant
             */
            readonly kind?: "option";
            /** Ask Id */
            readonly ask_id: string;
            /** Option Id */
            readonly option_id: string;
        };
        /**
         * Part
         * @description One thing the question asked for, and what became of it (§1).
         */
        readonly Part: {
            /** Part Id */
            readonly part_id: string;
            /** Text */
            readonly text: string;
            /**
             * Outcome
             * @enum {string}
             */
            readonly outcome: "answered" | "asked" | "refused" | "none";
            /** Reason */
            readonly reason: string | null;
            readonly ask: components["schemas"]["Ask"] | null;
        };
        /**
         * Refusal
         * @description A refusal that sinks the whole question: no part is answered.
         */
        readonly Refusal: {
            /**
             * Stage
             * @enum {string}
             */
            readonly stage: "parse" | "map" | "execute";
            /** Reason */
            readonly reason: string;
        };
        /**
         * Reply
         * @description Everything one job sends back. Parts may mix answered, none, asked and refused.
         */
        readonly Reply: {
            /**
             * Conversation Id
             * Format: uuid
             */
            readonly conversation_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            readonly job_id: string;
            readonly blocking: components["schemas"]["Refusal"] | null;
            /** Parts */
            readonly parts: readonly components["schemas"]["Part"][];
            readonly answer: components["schemas"]["AnswerView"] | null;
            /**
             * Status
             * @enum {string}
             */
            readonly status: "answered" | "partial" | "asked" | "refused";
        };
        /**
         * RoundView
         * @description One round of a reopened conversation.
         */
        readonly RoundView: {
            /** Round */
            readonly round: number;
            /**
             * Job Id
             * Format: uuid
             */
            readonly job_id: string;
            /**
             * Status
             * @enum {string}
             */
            readonly status: "queued" | "parsing" | "mapping" | "fetching" | "presenting" | "done" | "failed";
            /** Answers */
            readonly answers: readonly components["schemas"]["GivenAnswer"][];
            readonly reply: components["schemas"]["Reply"] | null;
            /** Message */
            readonly message: string | null;
        };
        /**
         * Series
         * @description One line of a line view.
         */
        readonly Series: {
            /** Label */
            readonly label: string;
            /** Rows */
            readonly rows: readonly number[];
        };
        /** StatView */
        readonly StatView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly kind: "stat";
            /** Title */
            readonly title: string;
            /** Row */
            readonly row: number;
        };
        /** UserCreate */
        readonly UserCreate: {
            /**
             * Email
             * Format: email
             */
            readonly email: string;
            /** Password */
            readonly password: string;
            /**
             * Is Active
             * @default true
             */
            readonly is_active?: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            readonly is_superuser?: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            readonly is_verified?: boolean | null;
            /** Invite Code */
            readonly invite_code: string;
        };
        /** UserRead */
        readonly UserRead: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /**
             * Email
             * Format: email
             */
            readonly email: string;
            /**
             * Is Active
             * @default true
             */
            readonly is_active?: boolean;
            /**
             * Is Superuser
             * @default false
             */
            readonly is_superuser?: boolean;
            /**
             * Is Verified
             * @default false
             */
            readonly is_verified?: boolean;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
        /** DoneEvent */
        readonly DoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly kind: "done";
            readonly reply: components["schemas"]["Reply"];
        };
        /** FailedEvent */
        readonly FailedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly kind: "failed";
            /** Message */
            readonly message: string;
        };
        /** StageEvent */
        readonly StageEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly kind: "stage";
            /**
             * Stage
             * @enum {string}
             */
            readonly stage: "queued" | "parsing" | "mapping" | "fetching" | "presenting";
            /** Seconds */
            readonly seconds: number;
        };
        readonly JobEvent: components["schemas"]["StageEvent"] | components["schemas"]["DoneEvent"] | components["schemas"]["FailedEvent"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly auth_cookie_login_api_auth_login_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/x-www-form-urlencoded": components["schemas"]["Body_auth_cookie_login_api_auth_login_post"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly auth_cookie_logout_api_auth_logout_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly register_register_api_auth_register_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UserCreate"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly oauth_github_cookie_authorize_api_auth_github_authorize_get: {
        readonly parameters: {
            readonly query?: {
                readonly scopes?: readonly string[];
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OAuth2AuthorizeResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly oauth_github_cookie_callback_api_auth_github_callback_get: {
        readonly parameters: {
            readonly query?: {
                readonly code?: string | null;
                readonly code_verifier?: string | null;
                readonly state?: string | null;
                readonly error?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly history_api_conversations_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["ConversationSummary"][];
                };
            };
        };
    };
    readonly ask_api_conversations_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["NewConversationIn"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly answer_api_conversations__conversation_id__answers_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly conversation_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["AnswersIn"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly conversation_api_conversations__conversation_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly conversation_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ConversationView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly job_api_jobs__job_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly job_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly events_api_jobs__job_id__events_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly job_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "text/event-stream": components["schemas"]["JobEvent"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly feedback_api_jobs__job_id__feedback_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly job_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly health_api_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly me_api_me_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
}
