"""add embedding columns to concept

Revision ID: 00b08d07eff8
Revises: d1ec76ee2152
Create Date: 2026-09-16 18:23:14.968302

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b08d07eff8'
down_revision: Union[str, Sequence[str], None] = 'd1ec76ee2152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate cannot see this: the ``vector`` column type below doesn't
    # exist until the pgvector extension is enabled. Must run before the
    # add_column calls. Not schema-qualified -- installs into the database's
    # default search_path (public), same as any other extension.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True), schema='xbrl')
    op.add_column('concept', sa.Column('embedding_source_text', sa.Text(), nullable=True), schema='xbrl')
    op.add_column('concept', sa.Column('embedding_source_hash', sa.String(length=64), nullable=True), schema='xbrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concept', 'embedding_source_hash', schema='xbrl')
    op.drop_column('concept', 'embedding_source_text', schema='xbrl')
    op.drop_column('concept', 'embedding', schema='xbrl')
    # ### end Alembic commands ###
    # Columns using the ``vector`` type are gone; safe to remove the extension.
    op.execute("DROP EXTENSION IF EXISTS vector")
