"""Add SIC classification columns to company

Revision ID: 3011d3c40ff8
Revises: 00b08d07eff8
Create Date: 2026-09-18 23:35:53.421586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3011d3c40ff8'
down_revision: Union[str, Sequence[str], None] = '00b08d07eff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('sic_code', sa.String(length=4), nullable=True), schema='xbrl')
    op.add_column('company', sa.Column('sic_description', sa.String(length=120), nullable=True), schema='xbrl')
    op.add_column('company', sa.Column('sic_office', sa.String(length=120), nullable=True), schema='xbrl')
    op.create_index(op.f('ix_xbrl_company_sic_code'), 'company', ['sic_code'], unique=False, schema='xbrl')
    op.create_index(op.f('ix_xbrl_company_sic_office'), 'company', ['sic_office'], unique=False, schema='xbrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xbrl_company_sic_office'), table_name='company', schema='xbrl')
    op.drop_index(op.f('ix_xbrl_company_sic_code'), table_name='company', schema='xbrl')
    op.drop_column('company', 'sic_office', schema='xbrl')
    op.drop_column('company', 'sic_description', schema='xbrl')
    op.drop_column('company', 'sic_code', schema='xbrl')
    # ### end Alembic commands ###
