"""add admin action and invite revocation

What the admin routes need, all additive: the audit log (`web.admin_action`),
and on `web.invite` who made it (`created_by`, null from the CLI) and when it
was revoked (`revoked_at`, never together with `used_at`). Design:
app/api/DESIGN.md section 11. The admin role's grants and the row-level
policies that keep an admin off an admin's row are not here but in
app/db/roles.py: they name roles, which are provisioned after migrating.

Autogenerated and read through (docs/ALEMBIC.md); nothing needed correcting.
Downgrade drops the audit log.

Revision ID: 966a8d209afd
Revises: 70e7ca6e7347
Create Date: 2026-09-30 23:10:53.159425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '966a8d209afd'
down_revision: Union[str, Sequence[str], None] = '70e7ca6e7347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('admin_email', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_email', sa.String(length=320), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("action IN ('deactivate', 'reactivate', 'end_sessions', 'reset_password', 'delete_user', 'create_invite', 'revoke_invite', 'read_trace')", name=op.f('ck_admin_action_admin_action_kind')),
    sa.ForeignKeyConstraint(['admin_id'], ['web.user.id'], name=op.f('fk_admin_action_admin_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_action')),
    schema='web'
    )
    op.create_index(op.f('ix_web_admin_action_created_at'), 'admin_action', ['created_at'], unique=False, schema='web')
    op.add_column('invite', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True), schema='web')
    op.add_column('invite', sa.Column('created_by', sa.UUID(), nullable=True), schema='web')
    op.create_foreign_key(op.f('fk_invite_created_by_user'), 'invite', 'user', ['created_by'], ['id'], source_schema='web', referent_schema='web', ondelete='SET NULL')
    op.create_check_constraint(op.f('ck_invite_revoked_or_used'), 'invite', 'revoked_at IS NULL OR used_at IS NULL', schema='web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_invite_revoked_or_used'), 'invite', schema='web', type_='check')
    op.drop_constraint(op.f('fk_invite_created_by_user'), 'invite', schema='web', type_='foreignkey')
    op.drop_column('invite', 'created_by', schema='web')
    op.drop_column('invite', 'revoked_at', schema='web')
    op.drop_index(op.f('ix_web_admin_action_created_at'), table_name='admin_action', schema='web')
    op.drop_table('admin_action', schema='web')
    # ### end Alembic commands ###
