"""initial xbrl schema

Revision ID: d1ec76ee2152
Revises: 
Create Date: 2026-08-30 18:58:30.769700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1ec76ee2152'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS xbrl")
    op.create_table('company',
    sa.Column('cik', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('entity_name', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('cik', name=op.f('pk_company')),
    sa.UniqueConstraint('id', name=op.f('uq_company_id')),
    schema='xbrl'
    )
    op.create_index(op.f('ix_xbrl_company_ticker'), 'company', ['ticker'], unique=False, schema='xbrl')
    op.create_table('concept',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('taxonomy', sa.Enum('dei', 'us-gaap', 'srt', name='taxonomy', schema='xbrl'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept')),
    sa.UniqueConstraint('taxonomy', 'name', name='uq_concept_taxonomy_name'),
    schema='xbrl'
    )
    op.create_table('filing',
    sa.Column('accession_number', sa.String(length=20), nullable=False),
    sa.Column('company_cik', sa.Integer(), nullable=False),
    sa.Column('form', sa.Enum('10-K', '10-Q', name='filing_form', schema='xbrl'), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.Enum('FY', 'Q1', 'Q2', 'Q3', name='fiscal_period', schema='xbrl'), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['company_cik'], ['xbrl.company.cik'], name=op.f('fk_filing_company_cik_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('accession_number', name=op.f('pk_filing')),
    schema='xbrl'
    )
    op.create_index('ix_filing_company_period', 'filing', ['company_cik', 'fiscal_year', 'fiscal_period'], unique=False, schema='xbrl')
    op.create_index('ix_filing_filed_date', 'filing', ['filed_date'], unique=False, schema='xbrl')
    op.create_index(op.f('ix_xbrl_filing_company_cik'), 'filing', ['company_cik'], unique=False, schema='xbrl')
    op.create_table('load_run',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('company_cik', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scope_forms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope_fiscal_years', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('taxonomy_count', sa.Integer(), nullable=True),
    sa.Column('concept_count', sa.Integer(), nullable=True),
    sa.Column('fact_count', sa.Integer(), nullable=True),
    sa.Column('units_allowlist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('facts_dropped_unit', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['company_cik'], ['xbrl.company.cik'], name=op.f('fk_load_run_company_cik_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load_run')),
    schema='xbrl'
    )
    op.create_index(op.f('ix_xbrl_load_run_company_cik'), 'load_run', ['company_cik'], unique=False, schema='xbrl')
    op.create_table('fact',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('filing_accession', sa.String(length=20), nullable=False),
    sa.Column('company_cik', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('is_instant', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('frame', sa.String(length=16), nullable=True),
    sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('(period_start IS NULL) = is_instant', name=op.f('ck_fact_instant_flag')),
    sa.CheckConstraint('period_start IS NULL OR period_start <= period_end', name=op.f('ck_fact_period_order')),
    sa.ForeignKeyConstraint(['company_cik'], ['xbrl.company.cik'], name=op.f('fk_fact_company_cik_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['xbrl.concept.id'], name=op.f('fk_fact_concept_id_concept'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['filing_accession'], ['xbrl.filing.accession_number'], name=op.f('fk_fact_filing_accession_filing'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact')),
    schema='xbrl'
    )
    op.create_index('ix_fact_concept_frame', 'fact', ['concept_id', 'frame'], unique=False, schema='xbrl')
    op.create_index('ix_fact_latest_lookup', 'fact', ['company_cik', 'concept_id', 'period_end'], unique=False, schema='xbrl', postgresql_where=sa.text('is_latest'))
    op.create_index(op.f('ix_xbrl_fact_company_cik'), 'fact', ['company_cik'], unique=False, schema='xbrl')
    op.create_index(op.f('ix_xbrl_fact_filing_accession'), 'fact', ['filing_accession'], unique=False, schema='xbrl')
    op.create_index('uq_fact_natural', 'fact', ['filing_accession', 'concept_id', 'unit', sa.literal_column('coalesce(period_start, period_end)'), 'period_end'], unique=True, schema='xbrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_fact_natural', table_name='fact', schema='xbrl')
    op.drop_index(op.f('ix_xbrl_fact_filing_accession'), table_name='fact', schema='xbrl')
    op.drop_index(op.f('ix_xbrl_fact_company_cik'), table_name='fact', schema='xbrl')
    op.drop_index('ix_fact_latest_lookup', table_name='fact', schema='xbrl', postgresql_where=sa.text('is_latest'))
    op.drop_index('ix_fact_concept_frame', table_name='fact', schema='xbrl')
    op.drop_table('fact', schema='xbrl')
    op.drop_index(op.f('ix_xbrl_load_run_company_cik'), table_name='load_run', schema='xbrl')
    op.drop_table('load_run', schema='xbrl')
    op.drop_index(op.f('ix_xbrl_filing_company_cik'), table_name='filing', schema='xbrl')
    op.drop_index('ix_filing_filed_date', table_name='filing', schema='xbrl')
    op.drop_index('ix_filing_company_period', table_name='filing', schema='xbrl')
    op.drop_table('filing', schema='xbrl')
    op.drop_table('concept', schema='xbrl')
    op.drop_index(op.f('ix_xbrl_company_ticker'), table_name='company', schema='xbrl')
    op.drop_table('company', schema='xbrl')
    # drop_table does not remove enum types -- drop them so a later re-run of
    # upgrade() doesn't fail with "type already exists".
    op.execute("DROP TYPE IF EXISTS xbrl.fiscal_period")
    op.execute("DROP TYPE IF EXISTS xbrl.filing_form")
    op.execute("DROP TYPE IF EXISTS xbrl.taxonomy")
    # ### end Alembic commands ###
