// @ts-check
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

module.exports = defineConfig([
  // Generated by `npm run api:types`; `npm run api:check` is what keeps it honest.
  { ignores: ['src/app/api/openapi.d.ts'] },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'vf',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'vf',
          style: 'kebab-case',
        },
      ],
      // The chart library is swappable because one component wraps it (DESIGN §5):
      // nothing outside src/app/answer/chart/ may import it.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['apexcharts', 'apexcharts/*', 'ng-apexcharts', 'ng-apexcharts/*'],
              message: 'Only src/app/answer/chart/ may use the chart library (DESIGN §5).',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/app/answer/chart/**/*.ts'],
    rules: { 'no-restricted-imports': 'off' }, // the one place that wraps the chart library
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {},
  },
]);
